export const FETCH_NEWS = 'FETCH_NEWS';
export const ADD_NEWS = 'ADD_NEWS';
export const DELETE_NEWS = 'DELETE_NEWS';

export const ADD_PRESS = 'ADD_PRESS';
export const UPDATE_PRESS = 'UPDATE_PRESS';
export const DELETE_PRESS = 'DELETE_PRESS';

export const TOGGLE_TAG_FILTER = 'TOGGLE_TAG_FILTER';
export const TOGGLE_PRESS_FILTER = 'TOGGLE_PRESS_FILTER';
export const SET_TIME_FILTER = 'SET_TIME_FILTER';

export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
export const DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION';

export const SET_FILTER_CONF = 'SET_FILTER_CONF';
export const SET_UPDATE_CONF = 'SET_UPDATE_CONF';
